### ISSUE TITLE
Exception catch problem

### ISSUE THREAD

**Issue by zy416548283** [kilim/kilim#55]
Hi, our team use kilim based on kilim1.0. Here, we has a problem about Exception-catch .
The problem we can reprodue by code:
```
package kilim.examples;

import kilim.Mailbox;
import kilim.Pausable;
import kilim.Task;

public class IllegalArException extends Task {
	public static void main(String[] args) {
		new IllegalArException().start();
	}

	public void execute() throws Pausable {
		int i = 2;
		try {
			new Mailbox<String>().get(1000);// RPC
			throw new DolphinRunException();
		} catch (DolphinRunException ex) {
			System.out.println("DolphinRunException:" + i);
		} catch (Exception ex) {
			System.out.println("Exception:" + i);
		}
	}

}

class DolphinRunException extends RuntimeException {
	
}
```
expect result:
```
DolphinRunException:2
```
but we get the result:
```
Exception:2
```

Thanks first.

**Comment by nqzero** [comment]
i've tried your example with my [kilim 2.0](https://github.com/nqzero/kilim) and it works correctly, most likely fixed by [this commit](https://github.com/nqzero/kilim/commit/329882d93378cd4e5142c8b52aa1fcaf9302d659). you should try to move to kilim 2.0

if there's something about 2.0 that is incompatible with your system let me know - it's possible that that commit will apply cleanly to 1.0, but i remember there being some subtleties when i fixed it

**Comment by zy416548283** [comment]
I move the commit change to kilim1.0, but the problem still exists.
Is there any other commit about the problem?

We want to move to kilim 2.0 and will try. There are many server-service online based on kilim 1.0.  Maybe this need some time.

**Comment by zy416548283** [comment]
@nqzero 

I have tried kilim2.0 for this problem. it works ok.

The kilim weave plugin can only run java 8 or higher version?
I run test with java 8 is ok, but change to java 7 then the result is
```
kilim/plugins/KilimMavenPlugin : Unsupported major.minor version 52.0
```

So java 7 should build with ant?
I get the message from kilim2.0 readme doc:
```
java 8 is the recommended platform, but should build (with ant), run and test under both 6 and 7
eg: JAVA_HOME=path/to/java7 ant clean weave jar
```

**Comment by nqzero** [comment]
i'm traveling till tuesday and don't have a java7 environment running on my laptop. at the least i messed up a commit (left out the effectively final -> final changes) - that should be pushed now (so pull again) but there may be other problems since i can't test

i'm not 100% sure what you're doing ? does your build depend on the maven plugin or are you able to use ant ? if you can use ant, the build should be very similar to the kilim 1.0 build (ie, copy the weaving block into your build.xml) now that i've (hopefully) fixed that bug

**Comment by zy416548283** [comment]
@nqzero 
I test the program again with kilim2.0.12.
The result seems that it has relation with the package name.
[class in the kilim.examples package](https://github.com/zy416548283/JavaBaseStudy/blob/master/pic/kilim_bug.png)

but in the com.tencent.java.kilim package, it works fine.

Can u reproduce it again?  Maybe I think the probolem is still exist.

**Comment by nqzero** [comment]
i'm able to reproduce with both 2.0.0-12 and -14. using the tencent package, i get the DolphinException, and using the kilim package, i get the plain (and incorrect) Exception

i'll track down the underlying issue - thanks for the excellent report

**Comment by nqzero** [comment]
@zy416548283 thanks for the very precise bug report about the exception reordering issue in kilim 2.0. this should be fixed in master on https://github.com/nqzero/kilim - specifically, in commit 72c7a2cea44139c55cb01a3a1dec040e760e164b

i still need to update the pom version and do a release, and i'll try to verify that the java 7 build is working (or fix it) tonight

**Comment by zy416548283** [comment]
Thanks, We will try kilim 2.0 in our services.
I have moved the commit to our team inner kilim version, it works fine now.
